server:
  port: 9010

spring:
  application:
    name: "message"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092