spring:
  application:
    name: transactions
  datasource:
    axis:
      url: jdbc:mysql://localhost:3306/axisdb
      username: root
      password: Mummagirl@123
      driver-class-name: com.mysql.cj.jdbc.Driver
    icici:
      url: jdbc:mysql://localhost:3306/icicidb
      username: root
      password: Mummagirl@123
      driver-class-name: com.mysql.cj.jdbc.Driver
    hdfc:
      url: jdbc:mysql://localhost:3306/hdfcdb
      username: root
      password: Mummagirl@123
      driver-class-name: com.mysql.cj.jdbc.Driver